# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'label.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import Resourcing_rc
import Resourcing_rc

class Ui_LabelWindow(object):
    def setupUi(self, LabelWindow):
        if not LabelWindow.objectName():
            LabelWindow.setObjectName(u"LabelWindow")
        LabelWindow.resize(1208, 900)
        icon = QIcon()
        icon.addFile(u":/newPrefix/drawing.png", QSize(), QIcon.Normal, QIcon.Off)
        LabelWindow.setWindowIcon(icon)
        self.frame2 = QFrame(LabelWindow)
        self.frame2.setObjectName(u"frame2")
        self.frame2.setGeometry(QRect(0, 440, 812, 406))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        brush2 = QBrush(QColor(127, 127, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush2)
        brush3 = QBrush(QColor(170, 170, 170, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        brush4 = QBrush(QColor(255, 255, 220, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush5 = QBrush(QColor(0, 0, 0, 128))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.frame2.setPalette(palette)
        self.frame2.setAutoFillBackground(True)
        self.frame2.setFrameShape(QFrame.StyledPanel)
        self.frame2.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget = QWidget(self.frame2)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(9, 5, 791, 401))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.lot2 = QLabel(self.verticalLayoutWidget)
        self.lot2.setObjectName(u"lot2")
        font = QFont()
        font.setPointSize(14)
        self.lot2.setFont(font)

        self.horizontalLayout_3.addWidget(self.lot2)

        self.label_4 = QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout_3.addWidget(self.label_4)


        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.line = QFrame(self.verticalLayoutWidget)
        self.line.setObjectName(u"line")
        self.line.setMinimumSize(QSize(28, 22))
        self.line.setBaseSize(QSize(23, 14))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.line.setPalette(palette1)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.verticalLayout_3.addWidget(self.line)

        self.resuls = QLabel(self.verticalLayoutWidget)
        self.resuls.setObjectName(u"resuls")
        self.resuls.setMinimumSize(QSize(0, 250))
        font1 = QFont()
        font1.setPointSize(12)
        self.resuls.setFont(font1)
        self.resuls.setInputMethodHints(Qt.ImhMultiLine)
        self.resuls.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.resuls.setWordWrap(True)

        self.verticalLayout_3.addWidget(self.resuls)

        self.frame = QWidget(LabelWindow)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 812, 406))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(812, 406))
        self.frame.setMaximumSize(QSize(812, 406))
        self.frame.setBaseSize(QSize(812, 406))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.frame.setPalette(palette2)
        self.frame.setAutoFillBackground(True)
        self.frame.setStyleSheet(u"QWidget{\n"
"background-color:white;\n"
"border: 8px black;\n"
"\n"
"}")
        self.horizontalwidget = QHBoxLayout(self.frame)
        self.horizontalwidget.setObjectName(u"horizontalwidget")
        self.horizontalwidget.setContentsMargins(-1, -1, 1, -1)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(530, 0))
        self.label.setMaximumSize(QSize(550, 100))
        self.label.setBaseSize(QSize(550, 0))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.label.setPalette(palette3)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QFrame.StyledPanel)
        self.label.setFrameShadow(QFrame.Sunken)
        self.label.setLineWidth(13)
        self.label.setPixmap(QPixmap(u":/newPrefix/ULS.jpg"))
        self.label.setScaledContents(False)

        self.verticalLayout_2.addWidget(self.label)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.batch_title = QLabel(self.frame)
        self.batch_title.setObjectName(u"batch_title")
        sizePolicy.setHeightForWidth(self.batch_title.sizePolicy().hasHeightForWidth())
        self.batch_title.setSizePolicy(sizePolicy)
        self.batch_title.setMaximumSize(QSize(550, 25))
        self.batch_title.setBaseSize(QSize(550, 0))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.batch_title.setPalette(palette4)
        self.batch_title.setFont(font)
        self.batch_title.setAutoFillBackground(False)
        self.batch_title.setStyleSheet(u"QLabel{\n"
"border: 5px black;\n"
"border-width: 5px;\n"
"}")
        self.batch_title.setFrameShape(QFrame.NoFrame)
        self.batch_title.setScaledContents(True)

        self.verticalLayout_2.addWidget(self.batch_title)

        self.verticalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_2.addItem(self.verticalSpacer_2)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)

        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)

        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)

        self.deliveryLabel = QLabel(self.frame)
        self.deliveryLabel.setObjectName(u"deliveryLabel")
        font2 = QFont()
        font2.setPointSize(10)
        self.deliveryLabel.setFont(font2)
        self.deliveryLabel.setScaledContents(True)

        self.gridLayout.addWidget(self.deliveryLabel, 5, 0, 1, 1)

        self.lotLabel = QLabel(self.frame)
        self.lotLabel.setObjectName(u"lotLabel")
        self.lotLabel.setFont(font2)
        self.lotLabel.setScaledContents(False)

        self.gridLayout.addWidget(self.lotLabel, 6, 0, 1, 1)

        self.expLabel = QLabel(self.frame)
        self.expLabel.setObjectName(u"expLabel")
        self.expLabel.setFont(font2)
        self.expLabel.setInputMethodHints(Qt.ImhDate)

        self.gridLayout.addWidget(self.expLabel, 4, 2, 1, 1)

        self.pHLabel = QLabel(self.frame)
        self.pHLabel.setObjectName(u"pHLabel")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.pHLabel.setPalette(palette5)
        self.pHLabel.setFont(font2)
        self.pHLabel.setAutoFillBackground(False)
        self.pHLabel.setStyleSheet(u"")
        self.pHLabel.setFrameShape(QFrame.VLine)
        self.pHLabel.setLineWidth(14)
        self.pHLabel.setMidLineWidth(7)
        self.pHLabel.setScaledContents(True)

        self.gridLayout.addWidget(self.pHLabel, 0, 0, 1, 1)

        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)

        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)

        self.dateLabel = QLabel(self.frame)
        self.dateLabel.setObjectName(u"dateLabel")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.dateLabel.sizePolicy().hasHeightForWidth())
        self.dateLabel.setSizePolicy(sizePolicy1)
        self.dateLabel.setFont(font2)
        self.dateLabel.setScaledContents(True)

        self.gridLayout.addWidget(self.dateLabel, 4, 0, 1, 1)

        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)

        self.conLabel = QLabel(self.frame)
        self.conLabel.setObjectName(u"conLabel")
        self.conLabel.setFont(font2)
        self.conLabel.setStyleSheet(u"QLabel{\n"
"border-width: 5px}")
        self.conLabel.setLineWidth(3)
        self.conLabel.setMidLineWidth(1)
        self.conLabel.setScaledContents(True)

        self.gridLayout.addWidget(self.conLabel, 1, 0, 1, 1)

        self.emailLabel = QLabel(self.frame)
        self.emailLabel.setObjectName(u"emailLabel")
        sizePolicy2 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.emailLabel.sizePolicy().hasHeightForWidth())
        self.emailLabel.setSizePolicy(sizePolicy2)
        self.emailLabel.setFont(font2)
        self.emailLabel.setScaledContents(True)
        self.emailLabel.setWordWrap(True)

        self.gridLayout.addWidget(self.emailLabel, 5, 2, 2, 1)

        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout.addWidget(self.label_5, 6, 2, 1, 1)


        self.horizontalLayout_2.addLayout(self.gridLayout)

        self.qrLabel = QLabel(self.frame)
        self.qrLabel.setObjectName(u"qrLabel")
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.qrLabel.sizePolicy().hasHeightForWidth())
        self.qrLabel.setSizePolicy(sizePolicy3)
        self.qrLabel.setMinimumSize(QSize(0, 0))
        self.qrLabel.setMaximumSize(QSize(150, 150))
        self.qrLabel.setSizeIncrement(QSize(1, 1))
        self.qrLabel.setAutoFillBackground(False)
        self.qrLabel.setScaledContents(True)

        self.horizontalLayout_2.addWidget(self.qrLabel)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)


        self.horizontalwidget.addLayout(self.verticalLayout_2)

        self.formLayout = QFormLayout()
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setFieldGrowthPolicy(QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setHorizontalSpacing(19)
        self.formLayout.setVerticalSpacing(18)
        self.formLayout.setContentsMargins(6, 10, 13, -1)
        self.corr = QLabel(self.frame)
        self.corr.setObjectName(u"corr")
        sizePolicy.setHeightForWidth(self.corr.sizePolicy().hasHeightForWidth())
        self.corr.setSizePolicy(sizePolicy)
        self.corr.setPixmap(QPixmap(u":/newPrefix/corrosive.png"))
        self.corr.setScaledContents(True)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.corr)

        self.resp = QLabel(self.frame)
        self.resp.setObjectName(u"resp")
        sizePolicy.setHeightForWidth(self.resp.sizePolicy().hasHeightForWidth())
        self.resp.setSizePolicy(sizePolicy)
        self.resp.setBaseSize(QSize(75, 75))
        self.resp.setAutoFillBackground(False)
        self.resp.setPixmap(QPixmap(u":/newPrefix/respiratory.png"))
        self.resp.setScaledContents(True)

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.resp)

        self.tox = QLabel(self.frame)
        self.tox.setObjectName(u"tox")
        sizePolicy.setHeightForWidth(self.tox.sizePolicy().hasHeightForWidth())
        self.tox.setSizePolicy(sizePolicy)
        self.tox.setPixmap(QPixmap(u":/newPrefix/toxic.png"))
        self.tox.setScaledContents(True)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.tox)

        self.haz = QLabel(self.frame)
        self.haz.setObjectName(u"haz")
        sizePolicy.setHeightForWidth(self.haz.sizePolicy().hasHeightForWidth())
        self.haz.setSizePolicy(sizePolicy)
        self.haz.setAutoFillBackground(False)
        self.haz.setPixmap(QPixmap(u":/newPrefix/warning.png"))
        self.haz.setScaledContents(True)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.haz)

        self.env = QLabel(self.frame)
        self.env.setObjectName(u"env")
        sizePolicy.setHeightForWidth(self.env.sizePolicy().hasHeightForWidth())
        self.env.setSizePolicy(sizePolicy)
        self.env.setPixmap(QPixmap(u":/newPrefix/environment.png"))
        self.env.setScaledContents(True)

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.env)

        self.flam = QLabel(self.frame)
        self.flam.setObjectName(u"flam")
        sizePolicy.setHeightForWidth(self.flam.sizePolicy().hasHeightForWidth())
        self.flam.setSizePolicy(sizePolicy)
        self.flam.setPixmap(QPixmap(u":/newPrefix/flammable.png"))
        self.flam.setScaledContents(True)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.flam)

        self.non = QLabel(self.frame)
        self.non.setObjectName(u"non")
        sizePolicy.setHeightForWidth(self.non.sizePolicy().hasHeightForWidth())
        self.non.setSizePolicy(sizePolicy)
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.non.setPalette(palette6)
        font3 = QFont()
        font3.setPointSize(9)
        self.non.setFont(font3)
        self.non.setAutoFillBackground(False)
        self.non.setPixmap(QPixmap(u":/newPrefix/Non haz.png"))
        self.non.setScaledContents(True)

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.non)

        self.hhmIcon = QLabel(self.frame)
        self.hhmIcon.setObjectName(u"hhmIcon")
        sizePolicy.setHeightForWidth(self.hhmIcon.sizePolicy().hasHeightForWidth())
        self.hhmIcon.setSizePolicy(sizePolicy)
        self.hhmIcon.setFont(font3)
        self.hhmIcon.setPixmap(QPixmap(u":/newPrefix/HHM.png"))
        self.hhmIcon.setScaledContents(True)

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.hhmIcon)


        self.horizontalwidget.addLayout(self.formLayout)

        self.buttonBox = QDialogButtonBox(LabelWindow)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(460, 390, 371, 61))
        self.buttonBox.setStyleSheet(u"QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)

        self.retranslateUi(LabelWindow)
        self.buttonBox.rejected.connect(LabelWindow.reject)

        QMetaObject.connectSlotsByName(LabelWindow)
    # setupUi

    def retranslateUi(self, LabelWindow):
        LabelWindow.setWindowTitle(QCoreApplication.translate("LabelWindow", u"Dialog", None))
        self.lot2.setText(QCoreApplication.translate("LabelWindow", u"TextLabel", None))
        self.label_4.setText(QCoreApplication.translate("LabelWindow", u"Page 2 of 2", None))
        self.resuls.setText(QCoreApplication.translate("LabelWindow", u"TextLabel", None))
        self.label.setText("")
        self.batch_title.setText(QCoreApplication.translate("LabelWindow", u"ABM 472 - ", None))
        self.label_8.setText("")
        self.label_9.setText("")
        self.label_6.setText("")
        self.deliveryLabel.setText(QCoreApplication.translate("LabelWindow", u"5th floor cold room", None))
        self.lotLabel.setText(QCoreApplication.translate("LabelWindow", u"Lot: A21739414", None))
        self.expLabel.setText(QCoreApplication.translate("LabelWindow", u"Exp: 05-31-25", None))
        self.pHLabel.setText(QCoreApplication.translate("LabelWindow", u"pH 4.76 @ 23.6 C ", None))
        self.label_2.setText("")
        self.label_3.setText("")
        self.dateLabel.setText(QCoreApplication.translate("LabelWindow", u"Date: 05-31-27", None))
        self.label_7.setText("")
        self.conLabel.setText(QCoreApplication.translate("LabelWindow", u"Conductivity: 14.5mS./m @ 24,5", None))
        self.emailLabel.setText(QCoreApplication.translate("LabelWindow", u"Email:ccmedders@amgen.com", None))
        self.label_5.setText("")
        self.qrLabel.setText(QCoreApplication.translate("LabelWindow", u"TextLabel", None))
        self.corr.setText("")
        self.resp.setText("")
        self.tox.setText("")
        self.haz.setText("")
        self.env.setText("")
        self.flam.setText("")
        self.non.setText("")
        self.hhmIcon.setText("")
    # retranslateUi

